from django.urls import path
from .views import UserRegistrationView, UserLoginView, VerifyOTPView, ResendOTPView, PatientProfileView,PatientProfileUpdateView, CheckEmailView,SendPasswordResetOTPView, VerifyPasswordResetOTPView, GoogleLoginView,BookingConfirmationByPaymentView,DoctorReviewListView,SubmitDoctorReviewView
from .views import ResetPasswordView, ChangePasswordView, UserLogoutView, DoctorListView, DoctorDetailView, DoctorSlotsView, CreatePaymentView, VerifyPaymentView, BookingHistoryView,AppointmentDetailView, ValidateVideoCallAPI,EmergencyDoctorListView,EmergencyConsultationListView
from .views import CreateEmergencyPaymentView, VerifyEmergencyPaymentView, ValidateEmergencyVideoCallAPI,EmergencyConsultationConfirmationView, ValidateChatAccessAPI, MedicalRecordListView, MedicalRecordDetailView,UserNotificationListView,ActiveDoctorsView,EmergencyConsultationDetailView
from .views import DownloadReceiptView,ContactMessageView

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(),name='login'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('resend-otp/', ResendOTPView.as_view(), name='verify_otp'),
    path('user-profile/', PatientProfileView.as_view(), name='patient_profile'),
    path('user-profile/update/', PatientProfileUpdateView.as_view(), name='patient_profile_update'),
    path('check-email/', CheckEmailView.as_view(), name='check_email'),
    path('send-password-reset-otp/', SendPasswordResetOTPView.as_view(), name='send_password_reset_otp'),
    path('verify-password-reset-otp/', VerifyPasswordResetOTPView.as_view(), name='verify-password-reset-otp'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('google/callback/', GoogleLoginView.as_view(), name='google_login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('doctors-list/',DoctorListView.as_view(), name='doctors-list' ),
    path('doctor-details/<slug:slug>/', DoctorDetailView.as_view(), name='doctor-details'),
    path('doctor-slots/<slug:slug>/', DoctorSlotsView.as_view(), name='doctor-slots'),
    path('payments/create/', CreatePaymentView.as_view(), name='create-payment'),
    path('payments/verify/', VerifyPaymentView.as_view(), name='verify-payment'),
    path('patient-bookings/', BookingHistoryView.as_view(), name='patient-booking-history'),
    path('emergency-consultations/',EmergencyConsultationListView.as_view(), name='emergency-consultation'),
    path('emergency-consultation-details/<int:consultation_id>',EmergencyConsultationDetailView.as_view(), name='emergency-consultation-details'),
    path('appointment-details/<int:appointment_id>',AppointmentDetailView.as_view(), name='appointment-details'),
    path('validate-videocall/<int:slot_id>/', ValidateVideoCallAPI.as_view(), name='validate_videocall'),
    path('booking-confirmation/payment/<str:payment_id>/',BookingConfirmationByPaymentView.as_view(),name='booking-confirmation-by-payment'),
    path('emergency-doctors/', EmergencyDoctorListView.as_view(), name='emergency-doctors'),
    path('emergency-payments/create/', CreateEmergencyPaymentView.as_view(), name='create-emergency-payment'),
    path('emergency-payments/verify/', VerifyEmergencyPaymentView.as_view(), name='verify-emergency-payment'),
    path('validate-emergency-video-call/<int:emergency_id>/', ValidateEmergencyVideoCallAPI.as_view(), name='validate-emergency-video-call'),
    path('emergency-confirmation/payment/<int:payment_id>/',EmergencyConsultationConfirmationView.as_view(),name='emergency-consultation-confirmation'),
    path('validate-chat/<int:slot_id>/',ValidateChatAccessAPI.as_view(), name='validate-chat'),
    path('records/', MedicalRecordListView.as_view(), name='medical-records-list'),
    path('records/<int:pk>/', MedicalRecordDetailView.as_view(), name='medical-record-detail'),
    path('user-notifications/', UserNotificationListView.as_view(), name='doctor-notifications'),
    path('active-doctors/', ActiveDoctorsView.as_view(), name='active-doctors'),
    path('doctor-reviews/<str:username>/', DoctorReviewListView.as_view(), name='get_doctor_reviews'),
    path('doctor-reviews/<str:username>/submit/', SubmitDoctorReviewView.as_view(), name='submit_doctor_review'),
    path('download-receipt/<int:appointment_id>/', DownloadReceiptView.as_view(), name='download-receipt'),
    path('contact/', ContactMessageView.as_view(), name='contact-message'),
]