# Generated by Django 5.0.3 on 2025-05-06 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$')]),
        ),
    ]
