# Generated by Django 5.0.3 on 2025-05-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_patientprofile_medical_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(default='registration', max_length=50),
        ),
    ]
