# Generated by Django 5.0.3 on 2025-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otpverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(default='password_reset', max_length=50),
        ),
    ]
