# Generated by Django 5.2.1 on 2025-06-19 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_appointment_unique_together_and_more'),
        ('doctor', '0029_doctorprofile_emergency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=800.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('consultation_started', models.BooleanField(default=False)),
                ('consultation_start_time', models.DateTimeField(blank=True, null=True)),
                ('consultation_end_time', models.DateTimeField(blank=True, null=True)),
                ('video_call_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_payments', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['payment_status'], name='accounts_em_payment_36d2b8_idx'), models.Index(fields=['timestamp'], name='accounts_em_timesta_bfbf3f_idx'), models.Index(fields=['payment_id'], name='accounts_em_payment_4042c0_idx'), models.Index(fields=['doctor', 'patient'], name='accounts_em_doctor__f57ac1_idx')],
            },
        ),
    ]
