# Generated by Django 5.2.1 on 2025-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypayment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
