# Generated by Django 5.2.1 on 2025-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_emergencypayment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, null=True),
        ),
    ]
