# Generated by Django 5.2.1 on 2025-06-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencypayment',
            name='video_call_link',
        ),
    ]
