# Generated by Django 5.2.1 on 2025-06-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_notification_content_type_notification_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
