# Generated by Django 5.2.1 on 2025-07-14 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_doctorreview'),
        ('doctor', '0031_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Report',
                'verbose_name_plural': 'Doctor Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
