# Generated by Django 5.2.1 on 2025-07-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_doctorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreport',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
