# Generated by Django 5.0.3 on 2025-05-10 03:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doctor',
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_certificates/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['registration_id'], name='doctor_doct_registr_967f81_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['is_approved'], name='doctor_doct_is_appr_7c751c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['gender'], name='doctor_doct_gender_13ce2b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['experience'], name='doctor_doct_experie_c6ebd9_idx'),
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
