# Generated by Django 5.0.3 on 2025-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
