# Generated by Django 5.0.3 on 2025-05-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_specialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
