# Generated by Django 5.0.3 on 2025-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_delete_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
