# Generated by Django 5.2.1 on 2025-06-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctorprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
