# Generated by Django 5.2.1 on 2025-06-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctorprofile_rating'),
    ]

    operations = [
    ]
