# Generated by Django 5.2.1 on 2025-06-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20250602_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='rating',
        ),
    ]
