# Generated by Django 5.2.1 on 2025-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_doctorprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
