# Generated by Django 5.2.1 on 2025-06-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_doctorprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='slug',
        ),
    ]
