# Generated by Django 5.2.1 on 2025-06-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_remove_doctorprofile_slug'),
    ]

    operations = [
    ]
