# Generated by Django 5.2.1 on 2025-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_doctorslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('chat', 'Online Chat')], max_length=10),
        ),
    ]
