# Generated by Django 5.2.1 on 2025-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_doctorslot_consultation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslot',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
