# Generated by Django 5.2.1 on 2025-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_doctorslot_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorslot',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
