# Generated by Django 5.2.1 on 2025-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_alter_doctorslot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslot',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
    ]
