# Generated by Django 5.2.1 on 2025-06-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_doctorslot_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
