# Generated by Django 5.2.1 on 2025-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_alter_doctorslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
