# Generated by Django 5.2.1 on 2025-06-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_wallet_wallethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='prefer_24hr_consultation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
