# Generated by Django 5.2.1 on 2025-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_doctorprofile_prefer_24hr_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='emergency_status',
            field=models.BooleanField(default=False),
        ),
    ]
