# Generated by Django 5.2.1 on 2025-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
