# Generated by Django 5.2.1 on 2025-07-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_alter_doctorprofile_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payout_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
