# Generated by Django 5.2.1 on 2025-07-19 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_doctorprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='doctor.doctorprofile'),
        ),
    ]
