# Generated by Django 5.2.1 on 2025-07-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_alter_wallet_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='cashfree_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
